config/routes.rb
Rails.application.routes.draw do

  devise_for :students, controllers: {
      registrations: 'student/registrations',
      sessions: 'student/sessions',
  }

  get 'lessons' => 'student/student#lessons'
  get 'teachers' => 'student/student#teachers'
  get 'subscriptions' => 'student/student#subscriptions'

  namespace :student do
    namespace :student do
      post 'subscribe', :path => 'subscribe/:id'
      post 'book_lesson', :path => 'book_lesson/:id'
      delete 'cancel_lesson', :path => 'cancel_lesson/:id'
      get 'get_teacher_schedule'
    end
  end

  root 'student/student#lessons'

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable, :registerable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, confirmation: true
  validates :password_confirmation, presence: true, on: :create

  has_one :subscription

end

app/controllers/student/registrations_controller.rb
class Student::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  before_filter :configure_permitted_parameters, :only => [:create]
  layout 'empty'

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if !resource.errors.empty?
      flash[:danger] = resource.errors.full_messages[0]
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password,:password_confirmation) }
  end

end

app/controllers/student/sessions_controller.rb
class Student::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  layout 'empty'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/student/student_controller.rb
class Student::StudentController < ApplicationController

  before_action :authenticate_student!

  def subscriptions
    @subscriptions = Subscription.all
  end

  def teachers
    page_num = 1
    if params[:page].present?
      page_num = Integer(params[:page]) rescue 1
    end

    keyword = params[:name]

    @teachers = Teacher.page(page_num).per(8)

    @teachers = @teachers.where('lower(name) LIKE :search', search: "%#{keyword.downcase}%") if keyword.to_s.strip.length > 0
    if params[:gender].present?
      @teachers = @teachers.where('gender IN (?)',params[:gender])
    end

    if params[:nationality].present? && params[:nationality][0].to_s.strip.length > 0
      @teachers = @teachers.where('nationality IN (?)',params[:nationality])
    end

    if params[:availability].present? && params[:availability].to_i == 1
      from_date = Date.strptime(params[:'from'],'%B %d, %Y') if params[:'from'].present?
      to_date = Date.strptime(params[:'to'],'%B %d, %Y') if params[:'to'].present?
      from_date = from_date || Date.today
      to_date = to_date || Date.today
      @teachers = @teachers.joins('inner join schedules on teachers.id = schedules.teacher_id').where('date(start_time) between ? and ? and schedule_status = 0',from_date,to_date).group('teachers.id')
    end

  end

  def get_teacher_schedule
    teacher_id = params[:teacher_id]

    @teacher = Teacher.where(:id => teacher_id).first
    if @teacher.nil?
      redirect_to teachers_path, :notice => 'Teacher doesn\'t exist' and return
    end

    raw_schedules = Schedule.where('teacher_id = ? and start_time > ? and start_time < ?', teacher_id.to_i,DateTime.now,(DateTime.now + 3.day))
    @hashed_schedules = Hash.new
    raw_schedules.each do |schedule|
      @hashed_schedules[schedule.start_time.strftime('%Y%m%d%H%M')] = schedule
    end
  end

  def lessons
    @lessons = Lesson.joins(schedule: [:teacher]).where('student_id = ? and start_time > ? and lesson_status = 1',current_student.id, DateTime.now).order('start_time ASC')
  end

  def book_lesson

    #validate that student has an active subscription
    subscription = Subscription.joins('inner join students on students.subscription_id = subscriptions.id').where('students.id = ?',current_student.id).first
    if subscription.nil?
      redirect_to subscriptions_path, :notice => 'You don\'t have an active subscription.' and return
    end

    #validate that schedule is available
    schedule_id = params[:id].to_i
    schedule = Schedule.where(:id => schedule_id).first
    if schedule.nil? || schedule.schedule_status == 1
      redirect_to teachers_path, :notice => 'The schedule is no longer available' and return
    end

    #validate max subscription
    active_lesson_count = Lesson.joins(:schedule).where('student_id = ? and lesson_date = ? and lesson_status = 1',current_student.id,schedule.start_time.to_date).count
    if active_lesson_count >= subscription.max_daily
      redirect_to teachers_path, :notice => 'Sorry you\'ve maxed out already on lessons for the day' and return
    end


    Schedule.transaction do

      schedule.update(:schedule_status => 1)

      lesson = Lesson.new(
          :schedule_id  => schedule_id,
          :student_id => current_student.id,
          :subscription_id => current_student.subscription_id,
          :lesson_status => 1,
          :lesson_date => schedule.start_time
      )
      unless lesson.save!
        raise ActiveRecord::Rollback
      end
    end

    redirect_to lessons_path, :notice => 'Successfully booked lesson'
  end

  def cancel_lesson
    lesson_id = params[:id].to_i
    lesson = Lesson.where(:id => lesson_id).first

    #validate that lesson exists and still active
    if lesson.nil? || lesson.lesson_status == 0
      redirect_to lessons_path, :notice => 'Lesson doesn\'t exist anymore' and return
    end

    schedule = Schedule.where(:id => lesson.schedule_id).first
    #validate cancellation of old lessons
    if schedule.nil? || schedule.start_time <= DateTime.now
      redirect_to lessons_path, :notice => 'Lesson doesn\'t exist anymore' and return
    end

    #open the teacher's schedule and set lesson inactive
    Schedule.transaction do
      schedule.update(:schedule_status => 0)
      lesson.update(:lesson_status => 0)
    end

    redirect_to lessons_path, :notice => 'Successfully Cancelled Lesson'
  end

  def subscribe
    student = Student.where(:id => current_student.id).first
    unless student.update!(:subscription_id => params[:id].to_i)
      redirect_to subscriptions_path, :notice => 'Failed to subscribe.' and return
    end
    current_student.subscription_id = params[:id].to_i
    redirect_to teachers_path, :notice => 'Successfully Subscribed to plan. You may not book lessons!'
  end

  private
  def student_authorized?
    unless student_signed_in?
      flash[:danger] = 'You are not authorized to view that page.'
      redirect_to new_student_registration_path
    end
  end

end

app/views/student/student/_schedule_table.html.erb
<h3 class="text-center">Schedule for <%= @teacher.name%></h3>
<div class="table-responsive">
  <table class="table table-bordered table-hover table-striped">
    <thead>
    <tr>
      <td></td>
      <%
         shown_dates = Array.new
      %>
      <!-- column headers -->
      <% (0..2).each do |i| %>
          <%
             d = (Date.today + i.day)
             shown_dates.push(d.strftime('%Y%m%d'))
          %>
          <th><%= d.strftime(EslBookingSystem::Application::DISPLAY_DATE_FORMAT) %></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% (0..23).each do |hour| %>
        <% [['00','30'],['30','00']].each_with_index do |minute,index| %>
            <tr>
              <th><%= hour.to_s+':'+minute[0].to_s+ ' - ' + (hour+index).to_s+':'+minute[1].to_s %></th>
              <% (0..2).each do |i| %>
                  <% slot_key = shown_dates[i]+('%02d' % hour) + minute[0].to_s %>
                  <%= content_tag :td,  {id: 'slot'+slot_key}  do %>
                    <% if @hashed_schedules.has_key?(slot_key) %>
                      <%
                        schedule = @hashed_schedules[slot_key]
                      %>
                      <% if schedule.schedule_status == 1 %>
                        <span>booked</span>
                      <% else %>
                        <%= link_to 'Open',student_student_book_lesson_path(schedule), method: :post, class:'btn btn-default' %>
                      <% end %>
                    <% end %>
                  <% end %>
              <% end %>
            </tr>
        <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/student/student/_search_form.html.erb
<%= form_tag teachers_path ,method: :get, :id=>'search-form', class:'form-horizontal'  do %>
    <div class="form-group form-inline">
      <%= label_tag :'teacher-search', class:'col-sm-2' do %>
          Teacher Name:
      <% end %>
      <div class="input-group col-sm-6">
        <input type="text" class="form-control search-param" placeholder="Search for..." id="teacher-search" name="name" value="<%=params[:name] %>">
              <span class="input-group-btn">
                    <button class="btn btn-default" id="btn-search">
                      <i class="fa fa-search"></i>
                    </button>
              </span>
      </div>
    </div>

    <div class="form-group form-inline">
      <%= label_tag :cbGender, class:'col-sm-2' do %>
          Gender:
      <% end %>
      <div class="col-sm4">
        <label class="checkbox-inline">
          <%= check_box_tag 'gender',Gender::MALE[0],params[:gender].present? && params[:gender].include?(Gender::MALE[0].to_s),id:'cbMale',name:'gender[]',class:'change-candidate' %><%= Gender::MALE[1] %>
        </label>
        <label class="checkbox-inline">
          <%= check_box_tag 'gender',Gender::FEMALE[0],params[:gender].present? && params[:gender].include?(Gender::FEMALE[0].to_s),id:'cbFemale',name:'gender[]',class:'change-candidate' %><%= Gender::FEMALE[1] %>
        </label>
      </div>
    </div>

    <div class="form-group form-inline">
      <%= label_tag :'sel-country', class:'col-sm-2' do %>
          Nationality:
      <% end %>
      <div class="col-sm-4">
        <%= country_select('nationality', '', { include_blank: 'Nationality', selected: (params[:nationality].present? ? params[:nationality][0] : nil) }, { class: 'form-control change-candidate', id:'sel-country'}) %>
      </div>
    </div>

    <div class="form-group form-inline">
      <%= label_tag :datepicker, class:'col-sm-2' do %>
          Availability:
      <% end %>
      <div class="input-daterange input-group col-sm-6" id="datepicker">
        <%= text_field_tag 'from',params[:from],class:'form-control dp-date change-candidate' %>
        <span class="input-group-addon">to</span>
        <%= text_field_tag 'to',params[:to],class:'form-control dp-date change-candidate' %>
      </div>
      <label class="checkbox-inline">
        <%= check_box_tag 'availability',1,params[:availability].to_i==1,id:'cbFilter',name:'availability',class:'change-candidate' %>Apply Schedule Filter
      </label>


    </div>


<% end %>

app/views/student/student/_teacher_list.html.erb
<div class="row">
  <% @teachers.each do |teacher| %>
      <div class="col-sm-3 col-lg-3 col-md-3">
        <%= content_tag :div, class:'thumbnail teacher-item',:data=>{id:teacher.id} do %>
            <%= image_tag 'http://placehold.it/320x150' %>
            <div class="caption">
              <h4>
                <%= teacher.name %>
              </h4>
              <small><%= Gender::parse_gender(teacher.gender)[1] %></small> - <small><%= ISO3166::Country[teacher.nationality].name %></small>
            </div>
        <% end %>
      </div>
  <% end %>
</div>
<div id="pagination-div" class="text-center">
  <%= paginate @teachers %>
</div>

app/views/student/student/get_teacher_schedule.js.erb
$('#schedule-div').html("<%= escape_javascript(render partial: 'schedule_table',collections: @hashed_schedules) %>");

app/views/student/student/lessons.html.erb
<%= stylesheet_link_tag 'student/lessons', media: 'all' %>
<%= stylesheet_link_tag 'student/student', media: 'all' %>
<%= javascript_include_tag 'student/lessons' %>

<% content_for :head_title do %>
    Lessons
<% end %>

<% if @lessons.nil? || @lessons.length == 0%>
    <h4>You currently have no available lessons.</h4>
<% end %>

<% @lessons.each do |lesson| %>
    <% schedule = lesson.schedule %>
    <div class="row">
      <div class="col-md-3">
        <%= content_tag :div, class:'thumbnail teacher-item' do %>
            <%= image_tag 'http://placehold.it/320x150' %>
            <div class="caption">
              <h4>
                <%= schedule.teacher.name %>
              </h4>
            </div>
        <% end %>
      </div>
      <div class="col-md-8">
            <h3><%= schedule.start_time.strftime(EslBookingSystem::Application::DISPLAY_DATE_FORMAT) %> - <small>(<%= schedule.start_time.strftime('%l:%M%p') %> - <%= schedule.end_time.strftime('%l:%M%p') %>)</small></h3>
            <%= link_to 'Cancel Lesson',student_student_cancel_lesson_path(lesson),method: :delete, class:'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/student/student/subscriptions.html.erb
<%= stylesheet_link_tag 'student/subscriptions', media: 'all' %>
<%= stylesheet_link_tag 'student/student', media: 'all' %>
<%= javascript_include_tag 'student/subscriptions' %>

<% content_for :head_title do %>
    Subscriptions
<% end %>


<div class="table-responsive">
  <table class="table table-bordered table-hover table-striped">
    <thead>
    <tr>
      <td>Name</td>
      <td>Max Lessons per day</td>
      <td>Subscribed</td>
    </tr>
    </thead>
    <tbody>
    <% @subscriptions.each do |subscription| %>
        <tr>
          <td><%= subscription.name %></td>
          <td><%= subscription.max_daily %></td>
          <td>
            <% if subscription.id == current_student.subscription_id %>
                Subscribed
            <% else %>
                <%= link_to 'Subscribe To Plan', student_student_subscribe_path(subscription), method: :post,class:'btn btn-default' %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/student/student/teachers.html.erb
<%= stylesheet_link_tag 'student/teachers', media: 'all' %>
<%= stylesheet_link_tag 'student/student', media: 'all' %>
<%= javascript_include_tag 'student/teachers' %>
<%= javascript_include_tag '/plugins/bootstrap-datepicker.min' %>
<%= stylesheet_link_tag '/plugins/bootstrap-datepicker.min' %>

<% content_for :head_title do %>
    Teachers
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= render :partial => 'search_form' %>
  </div>
  <div class="panel-body">
    <%= render :partial => 'teacher_list' %>
    <div id="schedule-div">
      <h4>Select Teacher for their Schedules.</h4>
    </div>
  </div>

  <div class="panel-footer">

  </div>
</div>
<%= hidden_field_tag :schedule_path , student_student_get_teacher_schedule_path %>