config/routes.rb
Rails.application.routes.draw do

  devise_for :students, controllers: {
      registrations: 'student/registrations',
      sessions: 'student/sessions',
  }

  get 'lessons' => 'student/student#lessons'
  get 'teachers' => 'student/student#teachers'
  get 'subscriptions' => 'student/student#subscriptions'

  namespace :student do
    namespace :student do
      post 'subscribe', :path => 'subscribe/:id'
      post 'book_lesson', :path => 'book_lesson/:id'
      delete 'cancel_lesson', :path => 'cancel_lesson/:id'
      get 'get_teacher_schedule'
    end
  end

  root 'student/student#lessons'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EslBookingSystem</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- Plugins -->
  <%= javascript_include_tag '/plugins/bootstrap-notify.min' %>
  <%= stylesheet_link_tag '/plugins/animate.min' %>

  <%= csrf_meta_tags %>
</head>
<body>
<p id="notice"><%= notice %></p>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ESL Booking System</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Lessons', lessons_path %>
        </li>
        <li>
          <%= link_to 'Teachers', teachers_path %>
        </li>
        <li>
          <%= link_to 'Subscriptions', subscriptions_path %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Hello '+ current_student.name+ '!', 'javascript:;' %>

        </li>
        <li>
          <%= link_to 'Log out', destroy_student_session_path, method: :delete %>
        </li>
      </ul>

    </div>




    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        <%= yield :head_title %>
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <%= yield %>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Your Website 2014</p>
      </div>
    </div>
    <!-- /.row -->
  </footer>

</div>
<!-- /.container -->


</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>ESL Booking System</title>
  <%= csrf_meta_tags %>
  <!-- Bootstrap Core CSS -->
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>

  <!-- Custom CSS -->


  <!-- Custom Fonts -->
  <!--<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->

  <!-- plugins -->


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Plugins -->
  <%= javascript_include_tag '/plugins/bootstrap-notify.min' %>
  <%= stylesheet_link_tag '/plugins/animate.min' %>

</head>

<body>
    <!-- p id="notice">< %= notice %></p -->
    <div id="wrapper">

    <div id="page-wrapper">

      <div class="container-fluid">
        <%= yield %>
      </div>
      <!-- /.container-fluid -->

    </div>
    <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

</body>

</html>